app1/urls.py
from app1.views import *
from django.urls import path
app_name='something'
urlpatterns=[
    path('janu/',janu,name='janu'),
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='nothing'
urlpatterns=[
    path('sree/',sree,name='sree'),
]

p11/urls.py
from django.contrib import admin
from django.urls import path,include
import app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def janu(request):
     return render(request,'janu.html') 

app2/views.py
from django.shortcuts import render

# Create your views here.
def sree(request):
    return render(request,'sree.html')

templates/janu.html
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>
    <center>
        <h1>Hello sree</h1>
        <h1>How are you</h1>
        <h1>I am good</h1>
        <h1>what is today plans</h1> 
        <h1>ok </h1>
        <a href="{% url 'nothing:sree' %}"><h1>response to sree>


        </h1></a>
    </center>
</body>
</html>

templates/sree.html
<!DOCTYPE html>
<html>
<head>
    
</head>
<body>
    <center>
        <h1>Hi janu</h1>
        <h1>I am fine u janu</h1>
        <h1>I will plan to going my sister house </h1>
        <a href="{% url 'something:janu' %}"><h1></h1>response to janu</h1></a>
    </center>
</body>
</html>